app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('products', 'ProductController');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;

class ProductController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $doc = new \DOMDocument();
        $doc->load('employees.xml');
        $employees = $doc->getElementsByTagName("employee");
        $doc->load('employees.xml');
        print_r($xml);
        return view('products.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $data = $request->all();
//        dd($data);

        $file = storage_path('products.xml');

        $xml = simplexml_load_file($file);
//dd($xml);
        $products = $xml->products;

        $product = $products->addChild('product');
        $product->addChild('name', 'a gallery');
        $product->addChild('qty', 'path/to/gallery');
        $product->addChild('price', 'mythumb.jpg');
        $product->addChild('created_at', 'mythumb.jpg');

        $xml->asXML($file);

//        $doc = new \DOMDocument();
//        $doc->load(storage_path('products.xml'));
//
//        $r = $doc->getElementsByTagName("products");
////        $doc->appendChild($r);
//
//        $b = $doc->createElement("product");
//
//        $name = $doc->createElement("name");
//        $name->appendChild(
//                $doc->createTextNode($data['name'])
//        );
//        $b->appendChild($name);
//
//        $qty = $doc->createElement("quantity");
//        $qty->appendChild(
//                $doc->createTextNode($data['quantity'])
//        );
//        $b->appendChild($qty);
//
//        $price = $doc->createElement("price");
//        $price->appendChild(
//                $doc->createTextNode($data['price'])
//        );
//        $b->appendChild($price);
//
//        $r->appendChild($b);
//
//        $doc->save(storage_path("/products.xml"));


        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/products/index.blade.php
<html>
    <head>
        <title>Coalition Laravel Test</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    </head>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <body>

        <div class="container-fluid" style="margin-top: 50px">
            {!! Form::open(['url'=>URL::route('products.store')]) !!}
            <div class="container"   style="width: 600px;">
                <div class="panel panel-primary">
                    <div class="panel-heading">Information of Product</div>
                    <div class="panel-body">
                        <div class="bs-example">
                        </div>
                        <div class="form-group">
                            {!! Form::label('name' , "Product Name") !!} <span class="text text-danger">*</span>
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Product Name', 'required' => 'true']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('qty' , "Quantity") !!} <span class="text text-danger">*</span>
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::text('quantity', null, ['class' => 'form-control', 'placeholder' => 'Quantity', 'required' => 'true']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('price' , "Price") !!} <span class="text text-danger">*</span>
                            <div class="row">
                                <div class="col-md-12">
                                    {!! Form::text('price', null, ['class' => 'form-control', 'placeholder' => 'Price', 'required' => 'true']) !!}
                                </div>
                            </div>
                        </div>
                        {!! isset($data) ? Form::hidden('address[id]', $data->people->addresses->first()->id) : '' !!}
                        <div class="box-footer pull-right">
                            {!! Form::submit('Save',['class'=>'btn btn-primary']) !!}
                        </div>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
            <div class="container">
                <table id="dataTableSelect" class="table table-bordered table-striped display">
                    <thead>
                        <tr>
                            <th>Product Name</th>
                            <th>Qty</th>
                            <th>Created</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($products))
                        @foreach($products as $key => $record)
                        <tr>
                            <td>{{$record->name}}</td>
                            <td>{{$record->qty}}</td>
                            <td>{{$record->price}}</td>
                            <td>{{$record->created_at}}</td>
                            <td class="text-center">
                                <a class="btn btn-default btn-sm" href="{{ URL::route('products.index',array('id'=>$record->id)) }}"><span class="fa fa-edit" aria-hidden="true"></span></a>
                                <a class="btn btn-default btn-sm ajax-del targetDel-{{ $record->people->id }}"
                                   data-toggle="modal" data-target="#delForm"
                                   data-url="{{ route('products.index', $record->id) }}"
                                   data-text="{{$record->name}}"
                                   data-id="{{ $record->id }}"
                                   href="#" >
                                    <span class="fa fa-trash" aria-hidden="true">
                                    </span>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                        @endif
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Product Name</th>
                            <th>Qty</th>
                            <th>Created</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>

        </div>
    </body>
</html>